// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 35 "The total is a number, not a formula".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson4.slide35

import presentation.support.*
import presentation.support.typed.generateExcel

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    column("Customer") { it.customer }
    column("Hours") { it.hours }
    column("Rate") { it.rate }
    column("Total") { it.hours * it.rate }
  }
}
