// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 36 "Columns become values we can reference".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson4.slide36

import presentation.support.*
import presentation.support.delegated.generateExcel

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    val customer by column { it.customer }
    val hours by column { it.hours }
    val rate by column { it.rate }
    val total by formula { hours * rate }
  }
}
