// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 39 "The total is a number, not a formula".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson4.slide39

import presentation.support.*
import presentation.support.typed.generateExcel

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    val customer by column { it.customer }
    val hours by column { it.hours }
    val rate by column { it.rate }
    val total by formula { hours * rate }
  }
}
