// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 39 "Two receivers, two `this`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson4.slide39

import presentation.support.*

interface Formulas {
  operator fun Column<Number>.times(other: Column<Number>): Cell
}

sealed interface Cell {
  data class Formula(val text: String) : Cell
  data class Value(val number: Double) : Cell
}

class ExcelFormulas(private val row: Int) : Formulas {
  override fun Column<Number>.times(other: Column<Number>): Cell =
    Cell.Formula("=$letter$row*${other.letter}$row")
}
