// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 42 "Only top-level extensions are static".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson4.slide42

import presentation.support.*

fun Column<*>.reference(row: Int): String = "$letter$row"

interface Formulas {
  operator fun Column<Number>.times(other: Column<Number>): Cell
}
