// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 44 "The receiver in scope picks the implementation".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson4.slide44

import presentation.support.*
import presentation.support.delegated.*

val total: Formulas.() -> Cell = { hours * rate }

suspend fun main() {
    ExcelFormulas(row = 2).total()

    Evaluate(mapOf(hours to 12, rate to 90)).total()
}
