// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 45 "The receiver type still checks".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson4.slide45

import presentation.support.*
import presentation.support.delegated.Formulas
import presentation.support.delegated.generateExcel

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    val customer by column { it.customer }
    val hours by column { it.hours }
    val rate by column { it.rate }
    val total by formula { rate * hours }
  }
}

//context(f: Formulas)
//operator fun Column<Number>.times(other: Column<Number>): Cell =
//  f.times(this, other)
