// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 13 "`Any?` accepts anything".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson2.slide13

import presentation.support.*
import presentation.support.marked.generateExcel

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    column("Customer") { it.customer }
    column("Invoice") { it }
  }
}
