// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 19 "Every column has a cell type".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson2.slide19

import presentation.support.*
import presentation.support.typed.generateExcel

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    column("Customer") { it.customer }
    column("Hours") { it.hours }
    column("Issued") { it.issuedOn }
  }
}
