// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 21 "Every column has a cell type".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson2.slide21

import presentation.support.*
import presentation.support.typed.generateExcel

fun SheetBuilder<Invoice>.column(name: String, block: (T) -> CustomType) {
  column(name) { block(it).toColumnText() }
}

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    column("Customer") { it.customer }
    column("Hours") { it.hours }
    column("Issued") { it.issuedOn }
    
    column("custom") { it.custom }
  }
}
