// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 22 "Every column has a cell type".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson2.slide22

import presentation.support.*
import presentation.support.typed.generateExcel

fun SheetBuilder<Invoice>.invoice() {
  column("Customer") { it.customer }
  column("Hours") { it.hours }
  column("Issued") { it.issuedOn }
}

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    invoice()
  }
}
