// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 54 "Varargs take any number of columns".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson6.slide54

import presentation.support.*
import presentation.support.varargs.*

interface Formulas {
  fun sum(vararg columns: Column<Number>): Cell
}

val subtotal by formula { sum(hours, overtime) }
