// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 54 "Accept a `List` instead".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson6.slide54

import presentation.support.*
import presentation.support.lists.*

interface Formulas {
  fun sum(columns: List<Column<Number>>): Cell
}

val subtotal by formula { sum(listOf(hours, overtime)) }

val billable = listOf(hours, overtime)

val total by formula { sum(billable) }
