// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 55 "Spread copies the array".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson6.slide55

import presentation.support.*
import presentation.support.varargs.*

interface Formulas {
  fun sum(vararg columns: Column<Number>): Cell
}

val subtotal by formula { sum(hours, overtime) }

val billable = arrayOf(hours, overtime)

val total by formula { sum(*billable) }
