// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 57 "Collection literals keep the call short".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson6.slide57

import presentation.support.*
import presentation.support.lists.*

interface Formulas {
  fun sum(columns: List<Column<Number>>): Cell
}

val subtotal by formula { sum([hours, overtime]) }

val billable = [hours, overtime]

val total by formula { sum(billable) }
