// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 62 "Operators build a tree".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson6.slide62

import presentation.support.*
import presentation.support.expressions.Formulas

sealed interface Expr {
  data class Ref(val column: Column<Number>) : Expr
  data class Constant(val value: Double) : Expr
  data class Times(val left: Expr, val right: Expr) : Expr
}

context(_: Formulas)
operator fun Column<Number>.times(other: Column<Number>): Expr =
  Expr.Times(Expr.Ref(this), Expr.Ref(other))

context(_: Formulas)
operator fun Expr.times(factor: Double): Expr =
  Expr.Times(this, Expr.Constant(factor))
