// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 63 "Rendering is a `when` over the tree".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson6.slide63

import presentation.support.*
import presentation.support.expressions.Expr

fun Expr.toExcel(row: Int): String = when (this) {
  is Expr.Ref -> column.reference(row)
  is Expr.Constant -> "$value"
  is Expr.Times -> "${left.toExcel(row)}*${right.toExcel(row)}"
  is Expr.Sum -> terms.joinToString(", ", "SUM(", ")") { it.toExcel(row) }
}
