// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 64 "Built once, rendered per row".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson6.slide64

import presentation.support.*
import presentation.support.expressions.generateExcel
import presentation.support.expressions.times

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    val customer by column { it.customer }
    val hours by column { it.hours }
    val rate by column { it.rate }
    val gross by formula { hours * rate * 1.21 }
  }
}
