// Generated by slidev-theme-kotlin from lessons/extra-sheets-as-values.md, slide 3 "`generateExcel` ties the schema to one file".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extrasheetsasvalues.slide3

import presentation.support.*
import presentation.support.delegated.generateExcel

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    val customer by column { it.customer }
    val hours by column { it.hours }
    val rate by column { it.rate }
    val total by formula { hours * rate }
  }
}
