// Generated by slidev-theme-kotlin from lessons/extra-sheets-as-values.md, slide 4 "A sheet is a value".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extrasheetsasvalues.slide4

import presentation.support.*
import kotlin.io.path.Path
import kotlin.io.path.outputStream
import presentation.support.contexts.times
import presentation.support.sheets.sheet

val invoiceSheet = sheet<Invoice> {
  val customer by column { it.customer }
  val hours by column { it.hours }
  val rate by column { it.rate }
  val total by formula { hours * rate }
}

suspend fun main() {
  Path("invoices.xlsx").outputStream().use { output ->
    invoiceSheet.write(output, invoices)
  }
}
