// Generated by slidev-theme-kotlin from lessons/extra-sheets-as-values.md, slide 5 "The schema is built once, rows at every `write`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extrasheetsasvalues.slide5

import presentation.support.*
import java.io.OutputStream
import presentation.support.sheets.sheet

val customers = sheet<Invoice> {
  println("schema")
  val customer by column { it.customer }
}

val rows = q1.onEach { println("row ${it.customer}") }

suspend fun main() {
  customers.write(OutputStream.nullOutputStream(), rows)

  customers.write(OutputStream.nullOutputStream(), rows)
}
