// Generated by slidev-theme-kotlin from lessons/extra-sheets-as-values.md, slide 7 "One schema, many row sets".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extrasheetsasvalues.slide7

import presentation.support.*
import kotlin.io.path.Path
import presentation.support.sheets.invoiceSheet
import presentation.support.sheets.write

suspend fun main() {
    invoiceSheet.write(Path("q1.xlsx"), q1)

    invoiceSheet.write(Path("q2.xlsx"), q2)
}
