// Generated by slidev-theme-kotlin from lessons/extra-sheets-as-values.md, slide 8 "Any `OutputStream` will do".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extrasheetsasvalues.slide8

import presentation.support.*
import com.sun.net.httpserver.HttpServer
import java.net.InetSocketAddress
import presentation.support.sheets.invoiceSheet

val server = HttpServer.create(InetSocketAddress(8080), 0)

suspend fun main() {
  server.createContext("/invoices.xlsx") { exchange ->
    exchange.sendResponseHeaders(200, 0)
    exchange.responseBody.use { body ->
      invoiceSheet.write(body, invoices)
    }
  }

  server.start()
}
