// Generated by slidev-theme-kotlin from lessons/extra-sheets-as-values.md, slide 9 "The schema is testable without a file".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extrasheetsasvalues.slide9

import presentation.support.*
import presentation.support.sheets.invoiceSheet

suspend fun main() {
    invoiceSheet.headers

    invoiceSheet.evaluate(invoices.first())
}
