// Generated by slidev-theme-kotlin from lessons/extra-sheets-as-values.md, slide 10 "A workbook composes sheets".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extrasheetsasvalues.slide10

import presentation.support.*
import kotlin.io.path.Path
import kotlin.io.path.outputStream
import presentation.support.sheets.invoiceSheet
import presentation.support.sheets.workbook

val report = workbook {
  sheet("Q1", invoiceSheet, q1)
  sheet("Q2", invoiceSheet, q2)
}

suspend fun main() {
  Path("report.xlsx").outputStream().use { report.write(it) }
}
