// Generated by slidev-theme-kotlin from lessons/extra-sheets-as-values.md, slide 11 "A global builder grows as classes load".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extrasheetsasvalues.slide11

import presentation.support.*
import presentation.support.delegated.Formulas
import presentation.support.delegated.SheetBuilder

val invoiceSheet = SheetBuilder<Invoice>()

val hours by invoiceSheet.column { it.hours }

val rate by invoiceSheet.column { it.rate }

val total by invoiceSheet.formula { hours * rate }

fun formula(block: Formulas.() -> Cell) = invoiceSheet.formula(block)
