// Generated by slidev-theme-kotlin from lessons/extra-sheets-as-values.md, slide 12 "A value needs no global".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extrasheetsasvalues.slide12

import presentation.support.*
import presentation.support.contexts.times
import presentation.support.contexts.withVat
import presentation.support.sheets.sheet

val invoiceSheet = sheet<Invoice> {
  val hours by column { it.hours }
  val rate by column { it.rate }
  val total by formula { hours * rate }
  val gross by formula { total.withVat() }
}

suspend fun main() {
  invoiceSheet.evaluate(invoices.first())["gross"]
}
