// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 45 "Users want their own formulas".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson5.slide45

import presentation.support.*
import presentation.support.delegated.Formulas
import presentation.support.delegated.formula
import presentation.support.delegated.total

interface Formulas {
  operator fun Column<Number>.times(other: Column<Number>): Cell
  operator fun Column<Number>.times(factor: Double): Cell
}

fun Formulas.withVat(column: Column<Number>): Cell = column * 1.21

val gross by formula { withVat(total) }
