// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 47 "A context parameter is not a receiver".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson5.slide47

import presentation.support.*
import presentation.support.delegated.Formulas
import presentation.support.delegated.formula
import presentation.support.delegated.total

interface Formulas {
  operator fun Column<Number>.times(other: Column<Number>): Cell
  operator fun Column<Number>.times(factor: Double): Cell
}

context(formulas: Formulas)
fun Column<Number>.withVat(): Cell = with(formulas) { this@withVat * 1.21 }

val gross by formula { total.withVat() }
