// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 50 "Declare the operators with a context".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson5.slide50

import presentation.support.*

interface Formulas {
  fun multiply(column: Column<Number>, other: Column<Number>): Cell
  fun multiply(column: Column<Number>, factor: Double): Cell
}

context(formulas: Formulas)
operator fun Column<Number>.times(factor: Double): Cell =
  formulas.multiply(this, factor)

context(formulas: Formulas)
fun Column<Number>.withVat(): Cell = this * 1.21
