// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 51 "A receiver satisfies a context".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson5.slide51

import presentation.support.*
import presentation.support.contexts.*

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    val hours by column { it.hours }
    val rate by column { it.rate }
    val total by formula { hours * rate }
    val gross by formula { total.withVat() }
  }
}
