// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 24 "Columns become values we can reference".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson3.slide24

import presentation.support.*
import presentation.support.delegated.generateExcel

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    val customer by column { it.customer }
    val hours by column { it.hours }
    val rate by column { it.rate }
  }
}
