// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 25 "The total is a number, not a formula".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson3.slide25

import presentation.support.*
import presentation.support.typed.generateExcel

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    column("Customer") { it.customer }
    val hours = column("Hours") { it.hours }
    val rate = column("Rate") { it.rate }
    column("Total") { hours * rate }
  }
}
