// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 26 "A delegate is just `getValue`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson3.slide26

import presentation.support.*

val entries = mapOf("one" to 1, "two" to 2)

val one by entries

suspend fun main() {
    println(entries.getValue(null, ::one))
}
