// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 28 "Columns become values we can reference".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson3.slide28

import presentation.support.*
import presentation.support.delegated.generateExcel

data class ExcelConfig(val columnNameStyle: (String) -> String)

companion val ExcelConfig.Default =
  ExcelConfig { it.replaceFirstChar(Char::uppercase) }

inline fun <T> generateExcel(
  path: String,
  rows: Sequence<T>,
  config: ExcelConfig = ExcelConfig.Default,
  block: SheetBuilder<T>.() -> Unit,
)

suspend fun main() {
  generateExcel("invoices.xlsx", invoices) {
    val customer by column { it.customer }
    val hours by column { it.hours }
    val rate by column { it.rate }
    column("Total") { hours * rate }
  }
}
