// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 31 "A delegate is just `getValue`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson3.slide31

import presentation.support.*
import kotlin.reflect.KProperty

val entries = mapOf("one" to 1, "two" to 2)

val one by entries

operator fun <V> Map<String, V>.getValue(
  thisRef: Any?,
  property: KProperty<*>,
): V = this[property.name]
  ?: throw NoSuchElementException("Key ${property.name} is missing")
