// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 32 "`ReadOnlyProperty` names the contract".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson3.slide32

import presentation.support.*
import kotlin.reflect.KProperty

fun interface ReadOnlyProperty<in T, out V> {
  operator fun getValue(thisRef: T, property: KProperty<*>): V
}
