// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 32 "`PropertyDelegateProvider` runs at the `by`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson3.slide32

import presentation.support.*
import kotlin.properties.PropertyDelegateProvider
import kotlin.properties.ReadOnlyProperty

@ExcelDsl
class SheetBuilder<T> {
  private val columns: MutableList<Column<*>> = mutableListOf()

  fun column(value: (T) -> Number) =
    PropertyDelegateProvider { _: Any?, property ->
      val column = Column<Number>(property.name, columns.size)
      columns.add(column)
      ReadOnlyProperty { _: Any?, _ -> column }
    }
}
