// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 35 "Registering in `getValue` is too late".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson3.slide35

import presentation.support.*
import kotlin.properties.ReadOnlyProperty

@ExcelDsl
class SheetBuilder<T> {
  private val columns: MutableList<Column<*>> = mutableListOf()

  fun column(value: (T) -> Number) = ReadOnlyProperty { _: Any?, property ->
    val column = Column<Number>(property.name, columns.size)
    columns.add(column)
    column
  }
}
