// Generated by slidev-theme-kotlin from lessons/extra-flow.md, slide 19 "Apache POI blocks, so it runs on `Dispatchers.IO`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extraflow.slide19

import presentation.support.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext
import presentation.support.flow.SheetBuilder

suspend fun <T> generateExcel(
  path: String,
  rows: Flow<T>,
  block: SheetBuilder<T>.() -> Unit,
) {
  val columns = SheetBuilder<T>().apply(block)
  withContext(Dispatchers.IO) {
    streamSheet(path, columns) { sheet -> rows.collect(sheet::write) }
  }
}
