// Generated by slidev-theme-kotlin from lessons/extra-flow.md, slide 21 "`collect` pulls one row at a time".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extraflow.slide21

import presentation.support.*
import kotlinx.coroutines.flow.onEach
import presentation.support.flow.fetchInvoices
import presentation.support.flow.generateExcel

val rows = fetchInvoices()
  .onEach { println("fetched ${it.customer}") }

suspend fun main() {
  generateExcel("invoices.xlsx", rows) {
    val customer by column {
      println("  wrote ${it.customer}")
      it.customer
    }
  }
}
