// Generated by slidev-theme-kotlin from lessons/extra-flow.md, slide 22 "Cancellation still deletes the temp files".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extraflow.slide22

import presentation.support.*
import kotlin.time.Duration.Companion.seconds
import kotlinx.coroutines.awaitCancellation
import kotlinx.coroutines.flow.emitAll
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.onEach
import kotlinx.coroutines.flow.take
import kotlinx.coroutines.withTimeoutOrNull
import presentation.support.flow.fetchInvoices
import presentation.support.flow.generateExcel
import presentation.support.flow.sxssfTempFiles

val stalled = flow {
  emitAll(fetchInvoices().take(2))
  awaitCancellation()
}.onEach { println("${it.customer}, ${sxssfTempFiles().size} temp file") }

suspend fun main() {
  withTimeoutOrNull(1.seconds) {
    generateExcel("invoices.xlsx", stalled) {
      val customer by column { it.customer }
    }
  } ?: println("Timed out, ${sxssfTempFiles().size} temp files")
}
