// Generated by slidev-theme-kotlin from lessons/extra-flow.md, slide 25 "Suspend in the `Flow`, not in the column".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package extras.snippets.extraflow.slide25

import presentation.support.*
import kotlinx.coroutines.flow.map
import presentation.support.flow.fetchEmail
import presentation.support.flow.fetchInvoices
import presentation.support.flow.generateExcel

data class Billed(val invoice: Invoice, val email: String)

val rows = fetchInvoices()
  .map { Billed(it, fetchEmail(it.customer)) }

suspend fun main() {
  generateExcel("invoices.xlsx", rows) {
    val customer by column { it.invoice.customer }
    val email by column { it.email }
  }
}
