// Generated by slidev-theme-kotlin from lessons/lesson-1.md, slide 4 "One file, many sheets".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson1.slide4

import presentation.support.*
import presentation.support.leaky.workbook

suspend fun main() {
  workbook("invoices.xlsx") {
    sheet("Q1", q1) {
      column("Customer", bold = true) { it.customer }
    }
    sheet("Q2", q2) {
      column("Customer", bold = true) { it.customer }
    }
  }
}
