// Generated by slidev-theme-kotlin from lessons/lesson-1.md, slide 9 "Implicit receivers stay in their own scope".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package snippets.lesson1.slide9

import presentation.support.*
import presentation.support.marked.workbook

suspend fun main() {
  workbook("invoices.xlsx") {
    sheet("Q1", q1) {
      column("Customer", bold = true) { it.customer }
      this@workbook.sheet("Q2", q2) {
        column("Customer", bold = true) { it.customer }
      }
    }
  }
}
